### ISSUE TITLE
Cannot publish images

### ISSUE THREAD

**Issue by han-kyung-min** [MIT-TESSE/tesse-ros-bridge#2]
Hello.

Thanks for the nice SW.
I am trying to publish images observed in TESSE to ROS using "tesse-ros-bridge" package.
To this end, I open two Linux terminals. Let's call them terminal A and terminal B. In terminal A, I start a python-mode. Then, successfully bring up a Goseek env using make_unity_env() function.

Now, I move to terminal B. Then, I execute "roslaunch tesse_ros_bridge tesse_bridge.launch" to start ROS nodes. 

Everything seems OK up to this point because I am able to echo all tesse messages such as /tesse/odom and /tesse/left_cam/image_raw. I was also able to see them in a Rviz window.

However, if I come back to terminal A, then give a command "env.step([1])", Then the system crashes with the error message below. How do we publish observation data to ROS during a training session in realtime?
Could you please help me with this issue?

Best

```
Traceback (most recent call last):
  File "goseek-ppo.py", line 140, in <module>
    main()
  File "goseek-ppo.py", line 114, in main
    env.reset()
  File "/home/hankm/python_ws/stable-baselines/stable_baselines/common/vec_env/dummy_vec_env.py", line 59, in reset
    obs = self.envs[env_idx].reset()
  File "/home/hankm/anaconda3/envs/goseek/lib/python3.7/site-packages/tesse_gym-0.1.6-py3.7.egg/tesse_gym/tasks/goseek/goseek.py", line 138, in reset
  File "/home/hankm/anaconda3/envs/goseek/lib/python3.7/site-packages/tesse_gym-0.1.6-py3.7.egg/tesse_gym/core/tesse_gym.py", line 242, in reset
  File "/home/hankm/anaconda3/envs/goseek/lib/python3.7/site-packages/tesse_gym-0.1.6-py3.7.egg/tesse_gym/core/tesse_gym.py", line 274, in get_synced_observation
  File "/home/hankm/anaconda3/envs/goseek/lib/python3.7/site-packages/tesse_gym-0.1.6-py3.7.egg/tesse_gym/tasks/goseek/goseek_full_perception.py", line 95, in observe
  File "/home/hankm/anaconda3/envs/goseek/lib/python3.7/site-packages/tesse_gym-0.1.6-py3.7.egg/tesse_gym/core/tesse_gym.py", line 374, in _data_request
  File "/home/hankm/python_ws/mit-tesse/tesse-interface/src/tesse/env.py", line 79, in request
    recv.bind((self.own_ip, self.get_port(msg)))
OSError: [Errno 98] Address already in use

```

**Comment by ZacRavichandran** [comment]
Thanks, glad you like it! 

The problem is due to a port conflict. The simulator exposes ports 9000-9005, the client binds to these while requesting data. By default, both the GOSEEK environment (in your terminal A) and ROS process (in terminal B) will try to bind to those ports, hence the `OSError: [Errno 98] Address already in use` error. 

The ROS process is designed to take data from the simulator and provide perception estimates (RGB, depth, segmentation, and pose). Thus, you can fix this issue by configuring the GOSEEK environment to read data from ROS. To do this, you will just need to change the `build_path` and `network_config` arguments. You can find an example of this in the [perception pipeline config](https://github.com/MIT-TESSE/goseek-challenge/blob/master/config/perception-pipeline.yaml) used by the [local evaluation script](https://github.com/MIT-TESSE/goseek-challenge/blob/master/test_locally.py). With `make_unity_env` it looks as follows:

```python

def make_unity_env(filename, num_env):
    """ Create a wrapped Unity environment. """

    def make_env(rank):
        def _thunk():
            env = GoSeekFullPerception(
                "",  # `sim_path` from perception-pipeline.yaml
                network_config=NetworkConfig(
                        image_port=9008,  # `image_port` from perception-pipeline.yaml
                        metadata_port=9007,  # `metadata_port` from perception-pipeline.yaml
                ),
                n_targets=n_targets,
                episode_length=episode_length,
                scene_id=scene_id[rank],
                target_found_reward=target_found_reward,
            )
            return env

        return _thunk

    return SubprocVecEnv([make_env(i) for i in range(num_env)])
```

With these changes, the workflow would be as follows:
1. Start the simulator: (by running `<GOSEEK_CHALLENGE_DIRECTORY>/simulator/goseek-v0.1.4.x86_64`)
2. Run ROS (`roslaunch tesse_ros_bridge tesse_bridge.launch`)
3. Launch the GOSEEK environment as above

Let me know if this helps!

**Comment by han-kyung-min** [comment]
Thanks for your help.

The problem certainly is at binding the same IP/port of the goseek env. 
My python training script and the rosnode were simultaneously attempting to bind the same ip/port. 
I agree with you that subscribing ros-msgs from the rosnode may solve the issue.
I tried your suggestion, but the system crashed w/ the error message below.


```
Traceback (most recent call last):
  File "navigation-ppo.py", line 144, in <module>
    main()
  File "navigation-ppo.py", line 118, in main
    env.reset()
  File "/home/hankm/python_ws/stable-baselines/stable_baselines/common/vec_env/dummy_vec_env.py", line 59, in reset
    obs = self.envs[env_idx].reset()
  File "/home/hankm/python_ws/mit-tesse/tesse-gym/src/tesse_gym/tasks/goseek/goseek.py", line 138, in reset
    super().reset(scene_id, random_seed)
  File "/home/hankm/python_ws/mit-tesse/tesse-gym/src/tesse_gym/core/tesse_gym.py", line 247, in reset
    observation = self.get_synced_observation()
  File "/home/hankm/python_ws/mit-tesse/tesse-gym/src/tesse_gym/core/tesse_gym.py", line 279, in get_synced_observation
    response = self.observe()
  File "/home/hankm/python_ws/mit-tesse/tesse-gym/src/tesse_gym/tasks/goseek/goseek_full_perception.py", line 95, in observe
    return self._data_request(DataRequest(metadata=True, cameras=cameras))
  File "/home/hankm/python_ws/mit-tesse/tesse-gym/src/tesse_gym/core/tesse_gym.py", line 383, in _data_request
    raise TesseConnectionError()
tesse_gym.core.utils.TesseConnectionError: Cannot receive data from the simulator. The connection is blocked or the simulator is not running.
```

I resolved the issue by changing IP address of my python script, though.

Thanks

**Comment by ZacRavichandran** [comment]
Glad you got it up and running!
